package hibernate;
// Generated 2017-04-17 18:03:07 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Measurement generated by hbm2java
 */
public class Measurement  implements java.io.Serializable {


     private int id;
     private Person person;
     private Date dateofMeasure;
     private double bodyWeight;
     private double neckSize;
     private double chestSize;
     private double waistSize;
     private double hipsSize;
     private double larmSize;
     private double rarmSize;
     private double lforearmSize;
     private double rforearmSize;
     private double lthighSize;
     private double rthighSize;
     private double lcalfSize;
     private double rcalfSize;

    public Measurement() {
    }

	
    public Measurement(int id, Date dateofMeasure, double bodyWeight, double neckSize, double chestSize, double waistSize, double hipsSize, double larmSize, double rarmSize, double lforearmSize, double rforearmSize, double lthighSize, double rthighSize, double lcalfSize, double rcalfSize) {
        this.id = id;
        this.dateofMeasure = dateofMeasure;
        this.bodyWeight = bodyWeight;
        this.neckSize = neckSize;
        this.chestSize = chestSize;
        this.waistSize = waistSize;
        this.hipsSize = hipsSize;
        this.larmSize = larmSize;
        this.rarmSize = rarmSize;
        this.lforearmSize = lforearmSize;
        this.rforearmSize = rforearmSize;
        this.lthighSize = lthighSize;
        this.rthighSize = rthighSize;
        this.lcalfSize = lcalfSize;
        this.rcalfSize = rcalfSize;
    }
    public Measurement(int id, Person person, Date dateofMeasure, double bodyWeight, double neckSize, double chestSize, double waistSize, double hipsSize, double larmSize, double rarmSize, double lforearmSize, double rforearmSize, double lthighSize, double rthighSize, double lcalfSize, double rcalfSize) {
       this.id = id;
       this.person = person;
       this.dateofMeasure = dateofMeasure;
       this.bodyWeight = bodyWeight;
       this.neckSize = neckSize;
       this.chestSize = chestSize;
       this.waistSize = waistSize;
       this.hipsSize = hipsSize;
       this.larmSize = larmSize;
       this.rarmSize = rarmSize;
       this.lforearmSize = lforearmSize;
       this.rforearmSize = rforearmSize;
       this.lthighSize = lthighSize;
       this.rthighSize = rthighSize;
       this.lcalfSize = lcalfSize;
       this.rcalfSize = rcalfSize;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Date getDateofMeasure() {
        return this.dateofMeasure;
    }
    
    public void setDateofMeasure(Date dateofMeasure) {
        this.dateofMeasure = dateofMeasure;
    }
    public double getBodyWeight() {
        return this.bodyWeight;
    }
    
    public void setBodyWeight(double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }
    public double getNeckSize() {
        return this.neckSize;
    }
    
    public void setNeckSize(double neckSize) {
        this.neckSize = neckSize;
    }
    public double getChestSize() {
        return this.chestSize;
    }
    
    public void setChestSize(double chestSize) {
        this.chestSize = chestSize;
    }
    public double getWaistSize() {
        return this.waistSize;
    }
    
    public void setWaistSize(double waistSize) {
        this.waistSize = waistSize;
    }
    public double getHipsSize() {
        return this.hipsSize;
    }
    
    public void setHipsSize(double hipsSize) {
        this.hipsSize = hipsSize;
    }
    public double getLarmSize() {
        return this.larmSize;
    }
    
    public void setLarmSize(double larmSize) {
        this.larmSize = larmSize;
    }
    public double getRarmSize() {
        return this.rarmSize;
    }
    
    public void setRarmSize(double rarmSize) {
        this.rarmSize = rarmSize;
    }
    public double getLforearmSize() {
        return this.lforearmSize;
    }
    
    public void setLforearmSize(double lforearmSize) {
        this.lforearmSize = lforearmSize;
    }
    public double getRforearmSize() {
        return this.rforearmSize;
    }
    
    public void setRforearmSize(double rforearmSize) {
        this.rforearmSize = rforearmSize;
    }
    public double getLthighSize() {
        return this.lthighSize;
    }
    
    public void setLthighSize(double lthighSize) {
        this.lthighSize = lthighSize;
    }
    public double getRthighSize() {
        return this.rthighSize;
    }
    
    public void setRthighSize(double rthighSize) {
        this.rthighSize = rthighSize;
    }
    public double getLcalfSize() {
        return this.lcalfSize;
    }
    
    public void setLcalfSize(double lcalfSize) {
        this.lcalfSize = lcalfSize;
    }
    public double getRcalfSize() {
        return this.rcalfSize;
    }
    
    public void setRcalfSize(double rcalfSize) {
        this.rcalfSize = rcalfSize;
    }



public String toString() {
    SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");
System.out.println(dt1.format(this.dateofMeasure));
         return dt1.format(this.dateofMeasure);
      }
}


