package hibernate;
// Generated 2017-04-17 18:03:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer id;
     private String nick;
     private String password;
     private String email;
     private String name;
     private String surname;
     private Date dateOfBirth;
     private Set measurements = new HashSet(0);

    public Person() {
    }

	
    public Person(String nick, String password, String name, String surname, Date dateOfBirth) {
        this.nick = nick;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.dateOfBirth = dateOfBirth;
    }
    public Person(String nick, String password, String email, String name, String surname, Date dateOfBirth, Set measurements) {
       this.nick = nick;
       this.password = password;
       this.email = email;
       this.name = name;
       this.surname = surname;
       this.dateOfBirth = dateOfBirth;
       this.measurements = measurements;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Set getMeasurements() {
        return this.measurements;
    }
    
    public void setMeasurements(Set measurements) {
        this.measurements = measurements;
    }




}


